Add greps

diff --git a/collection-scripts/gather_etcd b/collection-scripts/gather_etcd
--- a/collection-scripts/gather_etcd
+++ b/collection-scripts/gather_etcd
@@ -21,10 +21,38 @@ function ocp4etcdctl {
 }
 
 function ocp4nodes {
+    local bad=(
+        "No route"
+        "Connection refused"
+        "unreachable"
+        "could not resolve"
+        "name or service not known"
+        "Offset"
+        "Jitter"
+        "Stratum"
+        "fail"
+        "unable"
+        "not able"
+        "unsynchronized"
+        "Loaded configuration"
+        "Starting NTP client/server"
+        "Starting chronyd"
+        "chronyd version"
+    )
+    local good=(
+        "Loaded configuration"
+        "Starting NTP client/server"
+        "Starting chronyd"
+        "chronyd version"
+    )
+
     for node in ${ALL_CP_NODES}; do
         mkdir -p ${ETCD_LOG_PATH}/${node}
         echo "INFO: Gathering journald logs from node ${node}"
         oc debug "$node" -- chroot /host journalctl -u chronyd > "${ETCD_LOG_PATH}/${node}/journald.txt" 2>&1 || true
+
+        grep -i -E "${bad[*]}" "${ETCD_LOG_PATH}/${node}/journald.txt" && echo "ERROR: Found bad entries in journald logs for node ${node}" >&2 || true
+        grep -i -E "${good[*]}" "${ETCD_LOG_PATH}/${node}/journald.txt" || echo "WARNING: No good entries found in journald logs for node ${node}" >&2
     done
 }
 
